version: '3.8'
services:
  server:
    build: "."
    ports:
      - 8000:80
    volumes:
      - './:/var/www/html'
    networks:
      - app
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: cms
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - app
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - app
volumes:
  mysql:
    driver: local
networks:
  app:
    driver: bridge