version: '3.8'
services:
  server:
    build: "."
    ports:
      - 8000:80
    volumes:
      - './:/var/www/html'
    networks:
      - app
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cms
    ports:
      - 3306:3306
networks:
  app:
